### PR TITLE
Test my repo permissions

### PR DESCRIPTION
**Pull request by szepeviktor**

### CODE REVIEW

**Comment by szepeviktor** [comment]
> At least 1 approving review is required by reviewers with write access.

@leogermani Could you please approve this to see my permissions? (the merge button)

**Review by leogermani — APPROVED** [review]

**Comment by szepeviktor** [comment]
Thank you!

image

**Comment by szepeviktor** [comment]
Could you release v0.4.2?

**Comment by szepeviktor** [comment]
I'm sorry. I may have a small brain damage 🙃

**Pull request closed without merging**
